# Generated by Django 6.0.1 on 2026-03-21 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_voice_character_voice'),
    ]

    operations = [
        migrations.AddField(
            model_name='voice',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.userprofile'),
        ),
        migrations.AddField(
            model_name='voice',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
